%token BOOLT CHART INTT REALT STRINGT INTP CHARP REALP IF ELSE WHILE VAR FUNC PROC RETURN NULL MAIN
%token AND DIVIDE ASIGN COMPARE GREATER GREATEREQUAL LESS LESSEQUAL MINUS NOT NOTEQUAL OR PLUS MULTIPLY ADDRESS DEFERENCE
%token ENDLINE COLONS COMMA ABSOLUTE OBLOCK CBLOCK OLIST CLIST OINDIX CINDEX
%token BOOLEAN CHAR INTEGER REAL STRING COMMENT IDENTIFIER

%left PLUS MINUS RETURN
%left MULTIPLY DIVIDE
%left COMPARE GREATER GREATEREUAL LESS LESSEQUAL NOTEQUAL OR AND
%left ENDLINE